services:
  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  go:
    build:
      context: ./go
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - nextjs
      - go
      - django